### ISSUE TITLE
Cfs:gridfs crashed Meteor server

### ISSUE THREAD

**Issue by adamgins** [CollectionFS/Meteor-cfs-gridfs#14]
HI, Not sure if the error is in my code or somewhere in CFS. I was uploading an image (using cfs:s3). I think the image upload did not work. I tried to re-upload and ended up with this server crash (see below). Perhaps, I am just not exciting gracefully/catching the exception?

```
Feb 06 00:03:58 nodejs-app1 default:  error: uncaughtException: 54d36a3d496e1ca95257e131 does not exist 
Feb 06 00:03:58 nodejs-app1 default:  error:     { date: 'Thu Feb 05 2015 13:03:58 GMT+0000 (UTC)', 
Feb 06 00:03:58 nodejs-app1 default:  error:       process:  
Feb 06 00:03:58 nodejs-app1 default:  error:        { pid: 21161, 
Feb 06 00:03:58 nodejs-app1 default:  error:          uid: 0, 
Feb 06 00:03:58 nodejs-app1 default:  error:          gid: 0, 
Feb 06 00:03:58 nodejs-app1 default:  error:          cwd: '/srv/www/buzzy_test/releases/20150205125612/programs/server', 
Feb 06 00:03:58 nodejs-app1 default:  error:          execPath: '/usr/local/bin/node', 
Feb 06 00:03:58 nodejs-app1 default:  error:          version: 'v0.10.33', 
Feb 06 00:03:58 nodejs-app1 default:  error:          argv:  
Feb 06 00:03:58 nodejs-app1 default:  error:           [ '/usr/local/bin/node', 
Feb 06 00:03:58 nodejs-app1 default:  error:             '/srv/www/buzzy_test/current/server.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:             'program.json' ], 
Feb 06 00:03:58 nodejs-app1 default:  error:          memoryUsage:  
Feb 06 00:03:58 nodejs-app1 default:  error:           { rss: 241815552, 
Feb 06 00:03:58 nodejs-app1 default:  error:             heapTotal: 108692480, 
Feb 06 00:03:58 nodejs-app1 default:  error:             heapUsed: 75519872 } }, 
Feb 06 00:03:58 nodejs-app1 default:  error:       os:  
Feb 06 00:03:58 nodejs-app1 default:  error:        { loadavg:  
Feb 06 00:03:58 nodejs-app1 default:  error:           [ 0.009765625, 
Feb 06 00:03:58 nodejs-app1 default:  error:             0.10498046875, 
Feb 06 00:03:58 nodejs-app1 default:  error:             0.11767578125 ], 
Feb 06 00:03:58 nodejs-app1 default:  error:          uptime: 262221.337744977 }, 
Feb 06 00:03:58 nodejs-app1 default:  error:       trace:  
Feb 06 00:03:58 nodejs-app1 default:  error:        [ { column: 26, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 216, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 35, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 738, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 5, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: 'Cursor.close', 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 959, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: 'close', 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 17, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: 'Cursor.nextObject', 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 738, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: 'nextObject', 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 14, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: 'commandHandler', 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 713, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 9, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/db.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 1806, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 41, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/base.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: 'Server.Base._callHandler', 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 442, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: 'Base._callHandler', 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 18, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/server.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 485, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 5, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: '[object Object].MongoReply.parseBody', 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 68, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: 'MongoReply.parseBody', 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false }, 
Feb 06 00:03:58 nodejs-app1 default:  error:          { column: 20, 
Feb 06 00:03:58 nodejs-app1 default:  error:            file: '/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/server.js', 
Feb 06 00:03:58 nodejs-app1 default:  error:            function: '', 
Feb 06 00:03:58 nodejs-app1 default:  error:            line: 443, 
Feb 06 00:03:58 nodejs-app1 default:  error:            method: null, 
Feb 06 00:03:58 nodejs-app1 default:  error:            native: false } ], 
Feb 06 00:03:58 nodejs-app1 default:  error:       stack:  
Feb 06 00:03:58 nodejs-app1 default:  error:        [ 'Error: 54d36a3d496e1ca95257e131 does not exist', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at /srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:216:26', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at /srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js:738:35', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at Cursor.close (/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js:959:5)', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at Cursor.nextObject (/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js:738:17)', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at commandHandler (/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js:713:14)', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at /srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/db.js:1806:9', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at Server.Base._callHandler (/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at /srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:485:18', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at [object Object].MongoReply.parseBody (/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)', 
Feb 06 00:03:58 nodejs-app1 default:  error:          '    at [object Object].<anonymous> (/srv/www/buzzy_test/releases/20150205125612/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)' ] } 
```
Any hints on how I should start trying to debug this, pls? I do see:

`54d36a3d496e1ca95257e131 does not exist `

I was not 100% sure what's generating that?

regards

Adam

**Comment by konradryw** [comment]
I am having the same problem. FS.Collection.insert creates duplicates for me (see https://github.com/CollectionFS/Meteor-cfs-gridfs/issues/15) so I created I script that tries to remove the dubs after the insert. It works 3 out of 4 times but then I also get the:

54d36a3d496e1ca95257XXXX does not exist

and the app crashes. The id is different each time.
